from raylib import *

key_map = {
    KEY_ESCAPE: ('esc', {'modifiers': [], 'key': 'escape'}),
    KEY_F1: ('F1', {'modifiers': [], 'key': 'f1'}),
    KEY_F2: ('F2', {'modifiers': [], 'key': 'f2'}),
    KEY_F3: ('F3', {'modifiers': [], 'key': 'f3'}),
    KEY_F4: ('F4', {'modifiers': [], 'key': 'f4'}),
    KEY_F5: ('F5', {'modifiers': [], 'key': 'f5'}),
    KEY_F6: ('F6', {'modifiers': [], 'key': 'f6'}),
    KEY_F7: ('F7', {'modifiers': [], 'key': 'f7'}),
    KEY_F8: ('F8', {'modifiers': [], 'key': 'f8'}),
    KEY_F9: ('F9', {'modifiers': [], 'key': 'f9'}),
    KEY_F10: ('F10', {'modifiers': [], 'key': 'f10'}),
    KEY_F11: ('F11', {'modifiers': [], 'key': 'f11'}),
    KEY_F12: ('F12', {'modifiers': [], 'key': 'f12'}),
    KEY_GRAVE: ('`', {'modifiers': [], 'key': 'grave_accent_and_tilde'}),
    KEY_ONE: ('1', {'modifiers': [], 'key': '1'}),
    KEY_TWO: ('2', {'modifiers': [], 'key': '2'}),
    KEY_THREE: ('3', {'modifiers': [], 'key': '3'}),
    KEY_FOUR: ('4', {'modifiers': [], 'key': '4'}),
    KEY_FIVE: ('5', {'modifiers': [], 'key': '5'}),
    KEY_SIX: ('6', {'modifiers': [], 'key': '6'}),
    KEY_SEVEN: ('7', {'modifiers': [], 'key': '7'}),
    KEY_EIGHT: ('8', {'modifiers': [], 'key': '8'}),
    KEY_NINE: ('9', {'modifiers': [], 'key': '9'}),
    KEY_ZERO: ('0', {'modifiers': [], 'key': '0'}),
    KEY_MINUS: ('-', {'modifiers': [], 'key': 'hyphen'}),
    KEY_EQUAL: ('=', {'modifiers': [], 'key': 'equal_sign'}),
    KEY_BACKSPACE: ('delete', {'modifiers': [], 'key': 'delete_or_backspace'}),
    KEY_TAB: ('tab', {'modifiers': [], 'key': 'tab'}),
    KEY_Q: ('Q', {'modifiers': [], 'key': 'q'}),
    KEY_W: ('W', {'modifiers': [], 'key': 'w'}),
    KEY_E: ('E', {'modifiers': [], 'key': 'e'}),
    KEY_R: ('R', {'modifiers': [], 'key': 'r'}),
    KEY_T: ('T', {'modifiers': [], 'key': 't'}),
    KEY_Y: ('Y', {'modifiers': [], 'key': 'y'}),
    KEY_U: ('U', {'modifiers': [], 'key': 'u'}),
    KEY_I: ('I', {'modifiers': [], 'key': 'i'}),
    KEY_O: ('O', {'modifiers': [], 'key': 'o'}),
    KEY_P: ('P', {'modifiers': [], 'key': 'p'}),
    KEY_LEFT_BRACKET: ('[', {'modifiers': [], 'key': 'open_bracket'}),
    KEY_RIGHT_BRACKET: (']', {'modifiers': [], 'key': 'close_bracket'}),
    KEY_BACKSLASH: ('\\', {'modifiers': [], 'key': 'backslash'}),
    KEY_CAPS_LOCK: ('caps', {'modifiers': [], 'key': 'caps_lock'}),
    KEY_A: ('A', {'modifiers': [], 'key': 'a'}),
    KEY_S: ('S', {'modifiers': [], 'key': 's'}),
    KEY_D: ('D', {'modifiers': [], 'key': 'd'}),
    KEY_F: ('F', {'modifiers': [], 'key': 'f'}),
    KEY_G: ('G', {'modifiers': [], 'key': 'g'}),
    KEY_H: ('H', {'modifiers': [], 'key': 'h'}),
    KEY_J: ('J', {'modifiers': [], 'key': 'j'}),
    KEY_K: ('K', {'modifiers': [], 'key': 'k'}),
    KEY_L: ('L', {'modifiers': [], 'key': 'l'}),
    KEY_SEMICOLON: (';', {'modifiers': [], 'key': 'semicolon'}),
    KEY_APOSTROPHE: ('\'', {'modifiers': [], 'key': 'quote'}),
    KEY_ENTER: ('ret', {'modifiers': [], 'key': 'return'}),
    KEY_LEFT_SHIFT: ('shift', {'modifiers': ['left_shift'], 'key': ''}),
    KEY_Z: ('Z', {'modifiers': [], 'key': 'z'}),
    KEY_X: ('X', {'modifiers': [], 'key': 'x'}),
    KEY_C: ('C', {'modifiers': [], 'key': 'c'}),
    KEY_V: ('V', {'modifiers': [], 'key': 'v'}),
    KEY_B: ('B', {'modifiers': [], 'key': 'b'}),
    KEY_N: ('N', {'modifiers': [], 'key': 'n'}),
    KEY_M: ('M', {'modifiers': [], 'key': 'm'}),
    KEY_COMMA: (',', {'modifiers': [], 'key': 'comma'}),
    KEY_PERIOD: ('.', {'modifiers': [], 'key': 'period'}),
    KEY_SLASH: ('/', {'modifiers': [], 'key': 'slash'}),
    KEY_RIGHT_SHIFT: ('shift', {'modifiers': ['right_shift'], 'key': ''}),
    KEY_LEFT_CONTROL: ('ctrl', {'modifiers': ['left_control'], 'key': ''}),
    KEY_LEFT_ALT: ('opt', {'modifiers': ['left_alt'], 'key': ''}),
    KEY_LEFT_SUPER: ('cmd', {'modifiers': ['left_super'], 'key': ''}),  # Windows key or Command key
    KEY_SPACE: (' ', {'modifiers': [], 'key': 'spacebar'}),
    KEY_RIGHT_SUPER: ('cmd', {'modifiers': ['right_super'], 'key': ''}),
    KEY_RIGHT_ALT: ('opt', {'modifiers': ['right_alt'], 'key': ''}),
    KEY_RIGHT_CONTROL: ('ctrl', {'modifiers': ['right_control'], 'key': ''}),
    KEY_LEFT: ('left', {'modifiers': [], 'key': 'left_arrow'}),
    KEY_UP: ('up', {'modifiers': [], 'key': 'up_arrow'}),
    KEY_DOWN: ('down', {'modifiers': [], 'key': 'down_arrow'}),
    KEY_RIGHT: ('right', {'modifiers': [], 'key': 'right_arrow'})
}

def stringify_key_mod(modification):
    return '+'.join(modification['modifiers']) + '+' + modification['key']

# Reverse mappings
display_to_key = {v[0]: k for k, v in key_map.items()}
karabiner_to_key = {('+'.join(v[1]['modifiers']) + '+' + v[1]['key']): k for k, v in key_map.items()}
