import pyray as ray

rl_to_kb_key_map = {
    ray.KEY_ESCAPE: 'escape',
    ray.KEY_F1: 'f1',
    ray.KEY_F2: 'f2',
    ray.KEY_F3: 'f3',
    ray.KEY_F4: 'f4',
    ray.KEY_F5: 'f5',
    ray.KEY_F6: 'f6',
    ray.KEY_F7: 'f7',
    ray.KEY_F8: 'f8',
    ray.KEY_F9: 'f9',
    ray.KEY_F10: 'f10',
    ray.KEY_F11: 'f11',
    ray.KEY_F12: 'f12',
    ray.KEY_GRAVE: 'grave_accent_and_tilde',
    ray.KEY_ONE: '1',
    ray.KEY_TWO: '2',
    ray.KEY_THREE: '3',
    ray.KEY_FOUR: '4',
    ray.KEY_FIVE: '5',
    ray.KEY_SIX: '6',
    ray.KEY_SEVEN: '7',
    ray.KEY_EIGHT: '8',
    ray.KEY_NINE: '9',
    ray.KEY_ZERO: '0',
    ray.KEY_MINUS: 'hyphen',
    ray.KEY_EQUAL: 'equal_sign',
    ray.KEY_BACKSPACE: 'delete_or_backspace',
    ray.KEY_TAB: 'tab',
    ray.KEY_Q: 'q',
    ray.KEY_W: 'w',
    ray.KEY_E: 'e',
    ray.KEY_R: 'r',
    ray.KEY_T: 't',
    ray.KEY_Y: 'y',
    ray.KEY_U: 'u',
    ray.KEY_I: 'i',
    ray.KEY_O: 'o',
    ray.KEY_P: 'p',
    ray.KEY_LEFT_BRACKET: 'open_bracket',
    ray.KEY_RIGHT_BRACKET: 'close_bracket',
    ray.KEY_BACKSLASH: 'backslash',
    ray.KEY_CAPS_LOCK: 'caps_lock',
    ray.KEY_A: 'a',
    ray.KEY_S: 's',
    ray.KEY_D: 'd',
    ray.KEY_F: 'f',
    ray.KEY_G: 'g',
    ray.KEY_H: 'h',
    ray.KEY_J: 'j',
    ray.KEY_K: 'k',
    ray.KEY_L: 'l',
    ray.KEY_SEMICOLON: 'semicolon',
    ray.KEY_APOSTROPHE: 'quote',
    ray.KEY_ENTER: 'return',
    ray.KEY_LEFT_SHIFT: 'left_shift',
    ray.KEY_Z: 'z',
    ray.KEY_X: 'x',
    ray.KEY_C: 'c',
    ray.KEY_V: 'v',
    ray.KEY_B: 'b',
    ray.KEY_N: 'n',
    ray.KEY_M: 'm',
    ray.KEY_COMMA: 'comma',
    ray.KEY_PERIOD: 'period',
    ray.KEY_SLASH: 'slash',
    ray.KEY_RIGHT_SHIFT: 'right_shift',
    ray.KEY_LEFT_CONTROL: 'left_control',
    ray.KEY_LEFT_ALT: 'left_alt',
    ray.KEY_LEFT_SUPER: 'left_command',
    ray.KEY_SPACE: 'spacebar',
    ray.KEY_RIGHT_SUPER: 'right_command',
    ray.KEY_RIGHT_ALT: 'right_alt',
    ray.KEY_RIGHT_CONTROL: 'right_control',
    ray.KEY_LEFT: 'left_arrow',
    ray.KEY_UP: 'up_arrow',
    ray.KEY_DOWN: 'down_arrow',
    ray.KEY_RIGHT: 'right_arrow',
    ray.KEY_PRINT_SCREEN: 'print_screen',
    ray.KEY_SCROLL_LOCK: 'scroll_lock',
    ray.KEY_PAUSE: 'pause_break',
    ray.KEY_INSERT: 'insert',
    ray.KEY_HOME: 'home',
    ray.KEY_PAGE_UP: 'page_up',
    ray.KEY_DELETE: 'delete',
    ray.KEY_END: 'end',
    ray.KEY_PAGE_DOWN: 'page_down',
    ray.KEY_NUM_LOCK: 'num_lock',
    ray.KEY_KP_DIVIDE: 'keypad_divide',
    ray.KEY_KP_MULTIPLY: 'keypad_multiply',
    ray.KEY_KP_SUBTRACT: 'keypad_subtract',
    ray.KEY_KP_ADD: 'keypad_add',
    ray.KEY_KP_ENTER: 'keypad_enter',
    ray.KEY_KP_1: 'keypad_1',
    ray.KEY_KP_2: 'keypad_2',
    ray.KEY_KP_3: 'keypad_3',
    ray.KEY_KP_4: 'keypad_4',
    ray.KEY_KP_5: 'keypad_5',
    ray.KEY_KP_6: 'keypad_6',
    ray.KEY_KP_7: 'keypad_7',
    ray.KEY_KP_8: 'keypad_8',
    ray.KEY_KP_9: 'keypad_9',
    ray.KEY_KP_0: 'keypad_0',
    ray.KEY_KP_DECIMAL: 'keypad_decimal',
}

rl_to_display_key_map = {
    ray.KEY_ESCAPE: 'esc',
    ray.KEY_F1: 'f1',
    ray.KEY_F2: 'f2',
    ray.KEY_F3: 'f3',
    ray.KEY_F4: 'f4',
    ray.KEY_F5: 'f5',
    ray.KEY_F6: 'f6',
    ray.KEY_F7: 'f7',
    ray.KEY_F8: 'f8',
    ray.KEY_F9: 'f9',
    ray.KEY_F10: 'f10',
    ray.KEY_F11: 'f11',
    ray.KEY_F12: 'f12',
    ray.KEY_GRAVE: '`',
    ray.KEY_ONE: '1',
    ray.KEY_TWO: '2',
    ray.KEY_THREE: '3',
    ray.KEY_FOUR: '4',
    ray.KEY_FIVE: '5',
    ray.KEY_SIX: '6',
    ray.KEY_SEVEN: '7',
    ray.KEY_EIGHT: '8',
    ray.KEY_NINE: '9',
    ray.KEY_ZERO: '0',
    ray.KEY_MINUS: '-',
    ray.KEY_EQUAL: '=',
    ray.KEY_Q: 'Q',
    ray.KEY_W: 'W',
    ray.KEY_E: 'E',
    ray.KEY_R: 'R',
    ray.KEY_T: 'T',
    ray.KEY_Y: 'Y',
    ray.KEY_U: 'U',
    ray.KEY_I: 'I',
    ray.KEY_O: 'O',
    ray.KEY_P: 'P',
    ray.KEY_LEFT_BRACKET: '[',
    ray.KEY_RIGHT_BRACKET: ']',
    ray.KEY_BACKSLASH: '\\',
    ray.KEY_A: 'A',
    ray.KEY_S: 'S',
    ray.KEY_D: 'D',
    ray.KEY_F: 'F',
    ray.KEY_G: 'G',
    ray.KEY_H: 'H',
    ray.KEY_J: 'J',
    ray.KEY_K: 'K',
    ray.KEY_L: 'L',
    ray.KEY_SEMICOLON: ';',
    ray.KEY_APOSTROPHE: '\'',
    ray.KEY_Z: 'Z',
    ray.KEY_X: 'X',
    ray.KEY_C: 'C',
    ray.KEY_V: 'V',
    ray.KEY_B: 'B',
    ray.KEY_N: 'N',
    ray.KEY_M: 'M',
    ray.KEY_COMMA: ',',
    ray.KEY_PERIOD: '.',
    ray.KEY_SLASH: '/',
    ray.KEY_BACKSPACE: '⌫',
    ray.KEY_TAB: '⇥',
    ray.KEY_CAPS_LOCK: '⇪',
    ray.KEY_ENTER: '↵',
    ray.KEY_LEFT_SHIFT: '⇧',
    ray.KEY_RIGHT_SHIFT: '⇧',
    ray.KEY_SPACE: 'space',
    ray.KEY_LEFT_SUPER: '⌘',
    ray.KEY_RIGHT_SUPER: '⌘',
    ray.KEY_LEFT_ALT: '⌥',
    ray.KEY_RIGHT_ALT: '⌥',
    ray.KEY_LEFT_CONTROL: '⌃',
    ray.KEY_RIGHT_CONTROL: '⌃',
    ray.KEY_LEFT: '←',
    ray.KEY_UP: '↑',
    ray.KEY_DOWN: '↓',
    ray.KEY_RIGHT: '→',
    ray.KEY_PRINT_SCREEN: 'print',
    ray.KEY_SCROLL_LOCK: 'slock',
    ray.KEY_PAUSE: 'pause',
    ray.KEY_INSERT: 'ins',
    ray.KEY_HOME: '⇱',
    ray.KEY_PAGE_UP: '⇞',
    ray.KEY_DELETE: '⌦',
    ray.KEY_END: '⇲',
    ray.KEY_PAGE_DOWN: '⇟',
    ray.KEY_NUM_LOCK: '⇭',
    ray.KEY_KP_DIVIDE: 'keypad_/',
    ray.KEY_KP_MULTIPLY: 'keypad_*',
    ray.KEY_KP_SUBTRACT: 'keypad_-',
    ray.KEY_KP_ADD: 'keypad_+',
    ray.KEY_KP_ENTER: 'keypad_=',
    ray.KEY_KP_1: 'keypad_1',
    ray.KEY_KP_2: 'keypad_2',
    ray.KEY_KP_3: 'keypad_3',
    ray.KEY_KP_4: 'keypad_4',
    ray.KEY_KP_5: 'keypad_5',
    ray.KEY_KP_6: 'keypad_6',
    ray.KEY_KP_7: 'keypad_7',
    ray.KEY_KP_8: 'keypad_8',
    ray.KEY_KP_9: 'keypad_9',
    ray.KEY_KP_0: 'keypad_0',
    ray.KEY_KP_DECIMAL: 'keypad_.'
}

shift_mapping = {
    '1': '!',
    '2': '@',
    '3': '#',
    '4': '$',
    '5': '%',
    '6': '^',
    '7': '&',
    '8': '*',
    '9': '(',
    '0': ')',
    '-': '_',
    '=': '+',
    '[': '{',
    ']': '}',
    '\\': '|',
    ';': ':',
    "'": '"',
    ',': '<',
    '.': '>',
    '/': '?',
    '`': '~',
}
# Add letters mapping (lowercase to uppercase)
for letter in range(ord('a'), ord('z') + 1):
    shift_mapping[chr(letter)] = chr(letter - 32)  # Convert lowercase to uppercase

def get_shifted_key(key):
    return shift_mapping.get(key, key)

special_chars = set([ray.KEY_BACKSPACE,ray.KEY_TAB,ray.KEY_CAPS_LOCK,ray.KEY_ENTER,ray.KEY_LEFT_SHIFT,ray.KEY_RIGHT_SHIFT,
ray.KEY_LEFT_SUPER,ray.KEY_RIGHT_SUPER,ray.KEY_LEFT_ALT,ray.KEY_RIGHT_ALT,ray.KEY_LEFT_CONTROL,ray.KEY_RIGHT_CONTROL,ray.KEY_LEFT,ray.KEY_UP,
ray.KEY_DOWN,ray.KEY_RIGHT,ray.KEY_HOME,ray.KEY_PAGE_UP,ray.KEY_DELETE,ray.KEY_END,ray.KEY_PAGE_DOWN,ray.KEY_NUM_LOCK])

# Reverse mappings
kb_to_rl_key_map = {v: k for k, v in rl_to_kb_key_map.items()}
kb_to_rl_key_map['command'] = ray.KEY_LEFT_SUPER
kb_to_rl_key_map['control'] = ray.KEY_LEFT_CONTROL
kb_to_rl_key_map['left_option'] = ray.KEY_LEFT_ALT
kb_to_rl_key_map['right_option'] = ray.KEY_RIGHT_ALT

# Set of modification keys
modification_keys = set(['left_shift', 'right_shift', 'left_control', 'right_control', 'left_alt',
                     'right_alt', 'left_command', 'right_command'])