from raylib import *

rl_to_kb_key_map = {
    KEY_ESCAPE: 'escape',
    KEY_F1: 'f1',
    KEY_F2: 'f2',
    KEY_F3: 'f3',
    KEY_F4: 'f4',
    KEY_F5: 'f5',
    KEY_F6: 'f6',
    KEY_F7: 'f7',
    KEY_F8: 'f8',
    KEY_F9: 'f9',
    KEY_F10: 'f10',
    KEY_F11: 'f11',
    KEY_F12: 'f12',
    KEY_GRAVE: 'grave_accent_and_tilde',
    KEY_ONE: '1',
    KEY_TWO: '2',
    KEY_THREE: '3',
    KEY_FOUR: '4',
    KEY_FIVE: '5',
    KEY_SIX: '6',
    KEY_SEVEN: '7',
    KEY_EIGHT: '8',
    KEY_NINE: '9',
    KEY_ZERO: '0',
    KEY_MINUS: 'hyphen',
    KEY_EQUAL: 'equal_sign',
    KEY_BACKSPACE: 'delete_or_backspace',
    KEY_TAB: 'tab',
    KEY_Q: 'q',
    KEY_W: 'w',
    KEY_E: 'e',
    KEY_R: 'r',
    KEY_T: 't',
    KEY_Y: 'y',
    KEY_U: 'u',
    KEY_I: 'i',
    KEY_O: 'o',
    KEY_P: 'p',
    KEY_LEFT_BRACKET: 'open_bracket',
    KEY_RIGHT_BRACKET: 'close_bracket',
    KEY_BACKSLASH: 'backslash',
    KEY_CAPS_LOCK: 'caps_lock',
    KEY_A: 'a',
    KEY_S: 's',
    KEY_D: 'd',
    KEY_F: 'f',
    KEY_G: 'g',
    KEY_H: 'h',
    KEY_J: 'j',
    KEY_K: 'k',
    KEY_L: 'l',
    KEY_SEMICOLON: 'semicolon',
    KEY_APOSTROPHE: 'quote',
    KEY_ENTER: 'return',
    KEY_LEFT_SHIFT: 'left_shift',
    KEY_Z: 'z',
    KEY_X: 'x',
    KEY_C: 'c',
    KEY_V: 'v',
    KEY_B: 'b',
    KEY_N: 'n',
    KEY_M: 'm',
    KEY_COMMA: 'comma',
    KEY_PERIOD: 'period',
    KEY_SLASH: 'slash',
    KEY_RIGHT_SHIFT: 'right_shift',
    KEY_LEFT_CONTROL: 'left_control',
    KEY_LEFT_ALT: 'left_alt',
    KEY_LEFT_SUPER: 'left_super',
    KEY_SPACE: 'spacebar',
    KEY_RIGHT_SUPER: 'right_super',
    KEY_RIGHT_ALT: 'right_alt',
    KEY_RIGHT_CONTROL: 'right_control',
    KEY_LEFT: 'left_arrow',
    KEY_UP: 'up_arrow',
    KEY_DOWN: 'down_arrow',
    KEY_RIGHT: 'right_arrow'
}

# Reverse mappings
kb_to_rl_key_map = {v: k for k, v in rl_to_kb_key_map.items()}

# Set of modification keys
non_alpha_chars = {'left_shift', 'right_shift', 'left_control', 'right_control', 'left_alt', 'right_alt', 'left_super', 'right_super', 'caps_lock', 'tab', 'enter', 'backspace'}
modification_keys = {'left_shift', 'right_shift', 'left_control', 'right_control', 'left_alt', 'right_alt', 'left_super', 'right_super'}
