name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: macos-latest
    if: "contains(github.event.head_commit.message, 'Version ')"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install Poetry
      run: |
        pip3 install poetry

    - name: Install dependencies
      run: |
        poetry install

    - name: Activate virtual environment
      run: |
        echo "VIRTUAL_ENV=$(poetry env info --path)" >> $GITHUB_ENV
        echo "$(poetry env info --path)/bin" >> $GITHUB_PATH

    - name: Clean output directory
      run: |
        rm -rf dist/KarabinerKeyboard

    - name: Build app
      run: |
        poetry run bundle-app

    - name: Zip app
      run: |
        cd dist
        zip -r KarabinerKeyboard.zip KarabinerKeyboard.app

    - name: Get version from commit message
      run: |
        echo "version=$(echo "${{ github.event.head_commit.message }}" | grep -o 'Version [0-9]\+\.[0-9]\+\.[0-9]\+' | cut -d ' ' -f 2)" >> $GITHUB_ENV

    - name: Create release
      id: create_release
      uses: actions/create-release@v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.version }}
        release_name: Release ${{ env.version }}
        body: ${{ github.event.head_commit.message }}
        draft: false
        prerelease: false

    - name: Upload app
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/KarabinerKeyboard.zip
        asset_name: KarabinerKeyboard.zip
        asset_content_type: application/zip